version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
